### ISSUE TITLE
New feature: Allow Outputs for other Outputs / Direkt transmission to Webservers

### ISSUE THREAD

**Issue by Antibrumm** [boblemaire/IoTaWatt#238] opened 2019-10-20 15:45 UTC
Hi there.

First off: Happy new customer here 👍 The device is a great piece of work!

During the installation I found myself defining the same Output several times for different purposes. It would be great to be able to reuse them directly for other calculation and transmission to the webservers.

Example: 
Inputs: Heating_1, Heating_2, Heating_3

- Define one Output: Heatings = Heatings_1 + Heatings_2 + Heatings_3
- Define one Output: Unknown = Total - (Heatings_1 + Heatings_2 + Heatings_3)
=> Could become = Unknown = Total - Heatings

This pattern repeats also in the transmission setup, at least for InfluxDB:
- Heatings | Watts | = Heatings_1 + Heatings_2 + Heatings_3
- Heatings_dWh | Wh | = Heatings_1 + Heatings_2 + Heatings_3
- Unknown | Watts | = Total - (Heatings_1 + Heatings_2 + Heatings_3)

It would be great to avoid such double configurations. It's not a very big deal, as once you're done, you're done, but could simplify the setup process quite a bit. 

Cheers

**Comment by boblemaire** [comment] 2019-12-05 03:02
It wouldn't be hard to do on the face of it, but the devil is in the details.  While masquerading as a high level computer, the IoTaWatt is just a lowly IOT device with limited resources.  The problem is handling the error cases.  What happens to all those references if the referenced output disappears?   It's tempting to continue to add capability to the script system, but the possible problems when things are linked just snowballs.  Down the road, with maybe an ESP32, there may be room to redesign the datalog to accommodate something like this.
For now, I am closing this as it's not in the cards for the ESP8266.  Thanks.

**Closed by boblemaire** 2019-12-05 03:02 UTC
