### ISSUE TITLE
CT-values are not populated correctly

### ISSUE THREAD

**Issue by fredrike** [boblemaire/IoTaWatt#258] opened 2020-02-05 06:36 UTC
I have two inputs where the status-page shows values but the Graph+ and Influx db values are 0.

I switched input port for one and the problem went away for that port. But it would be interesting to see what the problem might be.

It is the VVB1 that is the problem in this picture:
<img width="612" alt="Screenshot 2020-02-05 at 7 21 05 " src="https://user-images.githubusercontent.com/676999/73816423-e351e000-47e8-11ea-9c69-f11b3b0e365c.png">
<img width="831" alt="Screenshot 2020-02-05 at 7 27 54 " src="https://user-images.githubusercontent.com/676999/73816500-15634200-47e9-11ea-9b94-f218bb43f00e.png">

Relevant configuration:

```json
{
	"format": 2,
	"timezone": "1",
	"device": {
		"name": "iotawatt",
		"version": 3,
		"channels": "15",
		"burden": [
			0,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24,
			24
		]
	},
	"inputs": [
		{
			"channel": 0,
			"name": "Voltage",
			"type": "VT",
			"model": "Ideal 77DE-06-09(EU)",
			"cal": 19.26,
			"vphase": 0,
			"vmult": 1
		},
		{
			"channel": 1,
			"name": "TM",
			"type": "CT",
			"model": "SCT013-000",
			"phase": 2.3,
			"turns": 2000,
			"cal": 83.33333333333333,
			"vphase": 120,
			"vmult": 1,
			"reverse": true
		},
		{
			"channel": 2,
			"name": "VVB1",
			"type": "CT",
			"model": "SCT013-000",
			"phase": 2.3,
			"turns": 2000,
			"cal": "83.33",
			"vphase": 240,
			"vmult": 1,
			"reverse": true,
			"signed": true
		},
		{
			"channel": 3,
			"name": "VVB2",
			"type": "CT",
			"model": "SCT013-000",
			"phase": 2.3,
			"turns": 2000,
			"cal": 83.33333333333333,
			"vphase": 0,
			"vmult": 1
		}
         ],
	"update": "ALPHA",
	"derive3ph": true,
         "dstrule": {
		"adj": 60,
		"utc": true,
		"begin": {
			"month": 3,
			"weekday": 1,
			"instance": -1,
			"time": 60
		},
		"end": {
			"month": 10,
			"weekday": 1,
			"instance": -1,
			"time": 60
		}
	}
}
```

**Comment by boblemaire** [comment] 2020-02-07 20:13
I don't have enough information to respond to this, but I have an idea what the issue is.  The support forum is a much more convenient tool for interacting and resolving problems.  Please resubmit there: [](https://community.iotawatt.com/latest)

**Closed by boblemaire** 2020-02-07 20:13 UTC
